on:
  push:
    branches:
      - main  # Trigger de actie bij pushes naar main

jobs:
  replace_alpha:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Zorg ervoor dat we de juiste branch uitchecken

      - name: Replace alpha_dev with alpha_prod
        run: |
          echo "Replacing alpha_dev with alpha_prod (case-insensitive)"
          # Vervang alle voorkomens van 'alpha_dev' (case-insensitive) door 'alpha_prod' in alle bestanden
          find . -type f -exec sed -i 's/alpha_dev/alpha_prod/Ig' {} +

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          
          # Voeg alle bestanden toe
          git add .  # Dit voegt alle gewijzigde bestanden toe
          
          # Commit de wijzigingen
          git commit -m "Replace alpha_dev with alpha_prod" || echo "No changes to commit"

      - name: Create a new branch
        run: |
          git checkout -b update-alpha

      - name: Push changes to the new branch
        run: |
          git push origin update-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-alpha  # De branch met wijzigingen
          base: main            # De doelbranch
          title: "Replace alpha_dev with alpha_prod"
          body: "Automatisch gegenereerde pull request om alpha_dev te vervangen door alpha_prod."
