on:
  push:
    branches:
      - main  # Trigger de actie bij pushes naar main

jobs:
  replace_alpha:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Zorg ervoor dat we de juiste branch uitchecken

      - name: Replace alpha_dev with alpha_prod
        run: |
          echo "Replacing alpha_dev with alpha_prod (case-insensitive)"
          # Vervang alle voorkomens van 'alpha_dev' (case-insensitive) door 'alpha_prod' in alle bestanden
          find . -type f -exec sed -i 's/alpha_dev/alpha_prod/Ig' {} +

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          
          # Voeg alle bestanden toe, behalve de workflow-bestanden
          git add .  # Dit voegt alle gewijzigde bestanden toe
          
          # Verwijder deploy-to-main.yml bestand uit de staging area (doe dit na git add)
          git reset .github/workflows/deploy-to-main.yml
          
          # Commit de wijzigingen
          git commit -m "Replace alpha_dev with alpha_prod" || echo "No changes to commit"

      - name: Push changes to main
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
